### ISSUE TITLE
报错Could not pass event InventoryMoveItemEvent to EnderCargo vBuild 1 zh-CN(SlimefunGuguProject) (git 04f339e)

### ISSUE THREAD

**Issue by fenglaosir** [SlimefunGuguProject/Ender-Cargo#3]
### 检查项目

- [X] 你使用的是从构建站下载的版本
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/EnderCargo/issues)，且没有找到相同的问题

### 问题描述

玩家进入游戏之后，后台不停报错Could not pass event InventoryMoveItemEvent to EnderCargo vBuild 1 zh-CN(SlimefunGuguProject) (git 04f339e)
这之后一段时间服务器会严重卡顿

### 复现步骤

1、放置大量的普通货运接口(没有末影接口)

### 预期行为

没有使用末影接口，什么都不会发生。

### 服务器日志

https://paste.guizhanss.net/pygCv

### 服务端软件

Purpur

### Minecraft 版本

1.20.1

### Slimefun版本

0021742-Beta

### 插件版本

Build 1 zh-CN(SlimefunGuguProject)(git 04f339e)

**Comment by ybw0014** [comment]
年久失修，已修复
